export const procedureList = [
  {id: 1, name: 'Aumento de pectorales', label: 'male', group: 'corporal'},
  {id: 2, name: 'Gluteoplastia', label: 'male', group: 'corporal'},
  {id: 3, name: 'Cirugia del abdomen', label: 'male', group: 'corporal'},
  {id: 4, name: 'Liposuccion laser', label: 'male', group: 'corporal'},
  {id: 5, name: 'Ginecomastia', label: 'male', group: 'corporal'},
  {id: 6, name: 'Aumento de pantorrillas', label: 'male', group: 'corporal'},
  {id: 7, name: 'Cirugia de nariz', label: 'male', group: 'facial'},
  {id: 8, name: 'Tratamiento de arrugar', label: 'male', group: 'facial'},
  {id: 9, name: 'Cirugia de parpados', label: 'male', group: 'facial'},
  {id: 10, name: 'Cirugia de menton', label: 'male', group: 'facial'},
  {id: 11, name: 'Lifting facial', label: 'male', group: 'facial'},
  {id: 12, name: 'Cirugia de orejas', label: 'male', group: 'facial'},
  {id: 13, name: 'Lifting de cuello', label: 'male', group: 'facial'},
  {id: 14, name: 'Reduccion de mejillas', label: 'male', group: 'facial'},

  //female

  {
    id: 15,
    name: 'Gluteoplastia',
    label: 'female',
    group: 'corporal',
    img: '/static/img/gluteoplastia-mujeres.jpg',
    questions: [
      {title: '¿Podré sentarme sin problemas y recibir inyecciones en los glúteos?', text: 'Preferiblemente, evite las inyecciones en las nalgas si tiene prótesis, ya que los implantes podrían ser pinchados Para sentarse no hay ninguna incomodidad, ya que, al sentarnos, las prótesis adoptan una ubicación privilegiada entre los músculos, lo cual impide que sean aplastadas.'},
      {title: '¿Cómo me quedarán las nalgas?', text: 'Con esta cirugía podrá mejorar su apariencia y autoestima, pero no necesariamente cambiará la apreciación que los demás tengan de usted o le proporcionará una figura perfecta. Antes de decidirse piense cuidadosamente en sus expectativas.'},
      {title: '¿Cuál es la ubicación correcta de las prótesis de glúteos?', text: 'Las mejores son aquellas que quedan entre los músculos, nunca las subcutáneas (debajo de la grasa)'},
      {title: '¿Cuál es la ventaja entre usar prótesis de glúteos e implantes inyectados?', text: 'Los implantes inyectados están siendo usados por un gran número de personas en todo el mundo: cirujanos plásticos, médicos esteticistas, peluqueros y todo aquel que quiera hacer dinero fácil, sin importar las complicaciones que esto pudiera generar. Estos implantes inyectados no son más que plásticos líquidos llamados de diferentes maneras para confundir a la colectividad y a aquellos que no saben de las complicaciones que acarrean. Los nombres que se están usando son: células expansivas, metacrilatos, biopolímeros, metacril y otras denominaciones orientadas al comercio. Estos plásticos nunca podrán ser retirados del organismo y las complicaciones que ocasionan serán por el resto de la vida. Vemos cómo, a diferencia de los implantes inyectados, las prótesis de glúteos pueden ser removidas, en caso de ser necesario, y sin las complicaciones que acarrean las inyecciones.'},
      {title: '¿Cuáles son las complicaciones de las prótesis glúteas?', text: 'La más temida es la infección, ya que la zona glútea -por razones obvias- es altamente contaminada. Otras incluyen hematomas, forma antiestética, retracción de la piel, dehiscencia de la sutura, inconformidad con el resultado.'},
      {title: '¿Cuándo está contraindicada esta cirugía?', text: 'En casos de tener alguna infección activa, alteraciones de la coagulación, alteraciones de la cicatrización, en pacientes inmunosuprimidas, embarazadas y/o con expectativas poco realistas.'},
      {title: '¿Cuánto es el tiempo de recuperación?', text: 'Los pacientes pueden irse a casa caminando. La sensación de dolor desaparecerá con el relajante muscular y analgésico indicados. Pueden sentarse luego del tercer día, reincorporarse al trabajo luego de una semana. Ejercicios tipo caminata a partir de las tres semanas. Recuperación completa luego de tres meses.'},
      {title: '¿Debo usar fajas?', text: 'Se debe usar una faja por un lapso de seis semanas, como es de rutina en casos de lipoescultura. Así la inflamación disminuye de una manera más rápida y las prótesis se mantienen en su posición indicada.'},
      {title: '¿Estas prótesis se cambian?', text: 'Estos implantes tienen una garantía de por vida. Deben cambiarse en casos de ruptura o contractura capsular. En ocasiones los pacientes piden recambio para aumentar volumen luego de varios años.'}
    ],
    detail: `<p>La gluteoplastia es el procedimiento mediante el cual se moldean las nalgas en caso de tener poco desarrollo de su musculatura, cúmulos de grasa desagradables en sus alrededores, trastornos adquiridos o malformaciones congénitas.</p><p>Las dos únicas alternativas seguras para realizar este procedimiento son:</p><p>Lipoinyección. Consiste en infiltración de grasa propia del paciente. La grasa obtenida de distintas partes del cuerpo, como abdomen y muslos, se prepara y enriquece con factores de crecimiento y luego se inyecta en los glúteos para mejorar forma y volumen.</p><p><strong>Implantes glúteos:</strong> prótesis de silicona diseñadas para mejorar el volumen y la forma de los glúteos.</p><p><strong>Candidatas:&nbsp;</strong></p><p>Mujeres con:</p><p>• poco desarrollo de los músculos glúteos.</p><p>• cúmulos de grasa en los alrededores de los glúteos que ocasionan deformidad o aspecto estético.</p><p>• trastornos adquiridos, como accidentes, quemaduras, etc.</p><p>• malformaciones congénitas, y</p><p>• atletas que a pesar de realizar ejercicios para aumentar los glúteos no consiguen resultados suficientes.</p><p>&nbsp;</p><p><strong>Nombre del procedimiento:</strong> GLUTEOPLASTIA</p><p><strong>Duración:</strong> De 2 a 3 horas, dependiendo de los elementos específicos del caso.</p><p><strong>Anestesia:</strong> General o peridural.</p><p><strong>Hospitalización:</strong> Ambulatoria o puede requerir una noche de hospitalización.</p><p><strong>Síntomas post-operatorios:</strong> Inflamación, dolor moderado, equimosis (morados).</p><p><strong>Riesgos:</strong> Dolor, hematomas, infección, lesión cutánea, asimetrías, trombosis.</p><p><strong>Recuperación:</strong></p><p>• Una semana para reintegrarse al trabajo.</p><p>• De 2 a 3 semanas para realizar ejercicios tipo caminatas.</p><p>• Tres meses de resolución completa para realizar cualquier tipo de ejercicio o fuerza.</p><p><strong>Duración de resultados:</strong> permanentes, siempre y cuanto se mantenga un peso estable.</p>`
  },
  {id: 16, name: 'Cirugia del abdomen', label: 'female', group: 'corporal'},
  {id: 17, name: 'Liposuccion laser', label: 'female', group: 'corporal'},
  {id: 18, name: 'Aumento de pantorrillas', label: 'female', group: 'corporal'},
  {id: 19, name: 'Aumento de mamas', label: 'female', group: 'corporal'},
  {id: 20, name: 'Reduccion de mamas', label: 'female', group: 'corporal'},
  {id: 21, name: 'Vulvoplastia', label: 'female', group: 'corporal'},
  {id: 22, name: 'Muslos (Cruroplastia)', label: 'female', group: 'corporal'},
  {id: 23, name: 'Renuvion', label: 'female', group: 'corporal'},
  {id: 24, name: 'Tratamiento de arrugas', label: 'female', group: 'facial'},
  {id: 25, name: 'Cirugia de menton', label: 'female', group: 'facial'},
  {id: 26, name: 'Cirugia de nariz', label: 'female', group: 'facial'},
  {id: 27, name: 'Lifting facial', label: 'female', group: 'facial'},
  {id: 28, name: 'Levantamiento de cejas', label: 'female', group: 'facial'},
  {id: 29, name: 'Cirugia de parpados', label: 'female', group: 'facial'},
  {id: 30, name: 'Reduccion de mejillas', label: 'female', group: 'facial'},
  {id: 31, name: 'Lifting de cuello', label: 'female', group: 'facial'},
  {id: 32, name: 'Cirugia de orejas', label: 'female', group: 'facial'},
  {id: 33, name: 'Toxina botulinica', label: 'female', group: 'treatments'},
]
