export const products = [
  {
    id: 1,
    img: '/static/dummy/example-product.jpg',
    discount: '15% dscto',
    isNew: true,
    buy: true,
    rent: false,
    price: '$6.000.000 + IVA',
    rating: 4.5,
    title: 'CUBETEADORA DE SEMI CONGELADO',
    isReserved: false,
    guaranty: true,
    maintenance: true
  },
  {
    id: 2,
    img: '/static/dummy/example-product.jpg',
    isNew: true,
    buy: true,
    rent: true,
    price: '$6.000.000 + IVA',
    rating: 3.5,
    title: 'CUBETEADORA DE SEMI CONGELADO',
    isReserved: true,
    guaranty: true,
    maintenance: true
  },
  {
    id: 3,
    img: '/static/dummy/example-product.jpg',
    discount: '25% dscto',
    isNew: false,
    buy: true,
    rent: true,
    price: '$6.000.000 + IVA',
    rating: 2.5,
    title: 'CUBETEADORA DE SEMI CONGELADO',
    isReserved: true,
    guaranty: true,
    maintenance: true
  },
  {
    id: 4,
    img: '/static/dummy/example-product.jpg',
    discount: false,
    isNew: true,
    buy: true,
    rent: true,
    price: '$6.000.000 + IVA',
    rating: 3.5,
    title: 'CUBETEADORA DE SEMI CONGELADO',
    isReserved: false,
    guaranty: true,
    maintenance: true
  },
  {
    id: 5,
    img: '/static/dummy/example-product.jpg',
    discount: '10% dscto',
    isNew: false,
    buy: false,
    rent: true,
    price: '$6.000.000 + IVA',
    rating: 4,
    title: 'CUBETEADORA DE SEMI CONGELADO',
    isReserved: false,
    guaranty: true,
    maintenance: true
  },
  {
    id: 6,
    img: '/static/dummy/example-product.jpg',
    isNew: true,
    buy: true,
    rent: true,
    price: '$6.000.000 + IVA',
    rating: 4.5,
    title: 'CUBETEADORA DE SEMI CONGELADO',
    isReserved: true,
    guaranty: true,
    maintenance: true
  },
]
